version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - docker/vault/development/.env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
