
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  password: password
  username: postgres

development:
  <<: *default
  database: nelson_development

test:
  <<: *default
  database: nelson_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['NELSON_DATABASE_URL'] %> # NELSON_DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
